export const STAGES = [
  { id: 'kuttsuki', name: 'くっつきことば', short: 'は・を・へ', description: 'ぶんに ぴったりな もじを えらぼう', icon: '🔗', color: '#ff7b67', badge: 'kuttsuki-clear' },
  { id: 'youon', name: 'ちいさい「ゃゅょ」', short: 'ゃ・ゅ・ょ', description: 'ちいさい もじを みつけよう', icon: '🔍', color: '#7b6cf6', badge: 'youon-clear' },
  { id: 'sokuon', name: 'ちいさい「っ」', short: 'ちいさい っ', description: 'つまる おとを みつけよう', icon: '🐾', color: '#14a98b', badge: 'sokuon-clear' },
  { id: 'choon', name: 'のばすおと', short: 'う・お・い・え', description: 'のばす おとの かきかたを えらぼう', icon: '🎈', color: '#e59b18', badge: 'choon-clear' }
];

const q = (id, stage, question, choices, answer, image, speak = null) => ({
  id, stage, question, choices, answer, image, speak: speak || question.replace('（　）', '')
});

export const QUESTIONS = [
  // くっつきことば：は/わ、を/お、へ/えを、文脈から選ぶ。正しい方を左右に混ぜる。
  q('k01', 'kuttsuki', 'わたし（　）いちねんせいです。', ['は', 'わ'], 0, '🙋', 'わたしは いちねんせいです'),
  q('k02', 'kuttsuki', 'きょう（　）はれです。', ['わ', 'は'], 1, '☀️', 'きょうは はれです'),
  q('k04', 'kuttsuki', 'みず（　）のみます。', ['お', 'を'], 1, '🥛', 'みずを のみます'),
  q('k05', 'kuttsuki', 'ほん（　）よみます。', ['を', 'お'], 0, '📖', 'ほんを よみます'),
  q('k06', 'kuttsuki', 'えんぴつ（　）つかいます。', ['お', 'を'], 1, '✏️', 'えんぴつを つかいます'),
  q('k07', 'kuttsuki', 'がっこう（　）いきます。', ['へ', 'え'], 0, '🏫', 'がっこうへ いきます'),
  q('k08', 'kuttsuki', 'こうえん（　）いきます。', ['え', 'へ'], 1, '🛝', 'こうえんへ いきます'),
  q('k09', 'kuttsuki', 'うち（　）かえります。', ['へ', 'え'], 0, '🏠', 'うちへ かえります'),
  q('k10', 'kuttsuki', 'ねこ（　）ねています。', ['わ', 'は'], 1, '🐈', 'ねこは ねています'),
  q('k11', 'kuttsuki', 'りんご（　）たべます。', ['を', 'お'], 0, '🍎', 'りんごを たべます'),
  q('k12', 'kuttsuki', 'としょかん（　）いきます。', ['え', 'へ'], 1, '📚', 'としょかんへ いきます'),
  q('k13', 'kuttsuki', 'ぼく（　）はしります。', ['は', 'わ'], 0, '🏃', 'ぼくは はしります'),
  q('k14', 'kuttsuki', 'は（　）みがきます。', ['お', 'を'], 1, '🪥', 'はを みがきます'),
  q('k15', 'kuttsuki', 'そら（　）とびます。', ['へ', 'え'], 0, '🕊️', 'そらへ とびます'),
  q('k16', 'kuttsuki', 'いぬ（　）げんきです。', ['わ', 'は'], 1, '🐕', 'いぬは げんきです'),
  // 「わ」「え」も、助詞ではなく言葉の一部になることを知る。
  q('k17', 'kuttsuki', '（　）が みずに います。', ['わに', 'はに'], 0, '🐊', 'わにが みずに います'),
  q('k18', 'kuttsuki', '（　）で えを ぬります。', ['えのぐ', 'へのぐ'], 0, '🎨', 'えのぐで えを ぬります'),
  q('k19', 'kuttsuki', '（　）を たべます。', ['おにぎり', 'をにぎり'], 0, '🍙', 'おにぎりを たべます'),
  q('k21', 'kuttsuki', 'うみで（　）を みつけました。', ['えび', 'へび'], 0, '🦐', 'うみで えびを みつけました'),
  q('k22', 'kuttsuki', '（　）は もりに います。', ['へび', 'えび'], 0, '🐍', 'へびは もりに います'),

  // 拗音：短い文の空欄に、正しい語を入れる。
  q('y01', 'youon', '（　）を のみます。', ['おちゃ', 'おちや'], 0, '🍵', 'おちゃを のみます'),
  q('y02', 'youon', '（　）を とります。', ['しゃしん', 'しやしん'], 0, '📷', 'しゃしんを とります'),
  q('y03', 'youon', '（　）を たべます。', ['きゅうり', 'きゆうり'], 0, '🥒', 'きゅうりを たべます'),
  q('y04', 'youon', '（　）を します。', ['ちょきん', 'ちよきん'], 0, '🐷', 'ちょきんを します'),
  q('y05', 'youon', '（　）に のります。', ['でんしゃ', 'でんしや'], 0, '🚃', 'でんしゃに のります'),
  q('y06', 'youon', 'あさに（　）を のみます。', ['ぎゅうにゅう', 'ぎゆうにゆう'], 0, '🥛', 'あさに ぎゅうにゅうを のみます'),
  q('y07', 'youon', 'なつに（　）へ いきます。', ['りょこう', 'りよこう'], 0, '🧳', 'なつに りょこうへ いきます'),
  q('y08', 'youon', '（　）を きります。', ['きゃべつ', 'きやべつ'], 0, '🥬', 'きゃべつを きります'),
  q('y09', 'youon', 'いえで（　）を します。', ['しゅくだい', 'しゆくだい'], 0, '✏️', 'いえで しゅくだいを します'),
  q('y10', 'youon', 'びょうきで（　）へ いきます。', ['びょういん', 'びよういん'], 0, '🏥', 'びょうきで びょういんへ いきます'),
  q('y11', 'youon', 'ともだちと（　）を します。', ['じゃんけん', 'じやんけん'], 0, '✊', 'ともだちと じゃんけんを します'),
  q('y12', 'youon', 'おいしゃさんが（　）を します。', ['ちゅうしゃ', 'ちゆうしや'], 0, '💉', 'おいしゃさんが ちゅうしゃを します'),
  q('y13', 'youon', '（　）まで かぞえます。', ['ひゃく', 'ひやく'], 0, '💯', 'ひゃくまで かぞえます'),
  q('y14', 'youon', '（　）で あそびます。', ['にんぎょう', 'にんぎよう'], 0, '🎎', 'にんぎょうで あそびます'),
  q('y15', 'youon', 'えほんに（　）が でます。', ['りゅう', 'りゆう'], 0, '🐉', 'えほんに りゅうが でます'),
  q('y16', 'youon', '（　）で べんきょうします。', ['きょうしつ', 'きようしつ'], 0, '🏫', 'きょうしつで べんきょうします'),

  // 促音：文の意味に合う「っ」のある語を選ぶ。
  q('s01', 'sokuon', '（　）で べんきょうします。', ['がっこう', 'がこう'], 0, '🏫', 'がっこうで べんきょうします'),
  q('s02', 'sokuon', 'はがきに（　）を はります。', ['きって', 'きて'], 0, '✉️', 'はがきに きってを はります'),
  q('s03', 'sokuon', '（　）の おとが します。', ['らっぱ', 'らぱ'], 0, '🎺', 'らっぱの おとが します'),
  q('s04', 'sokuon', 'でんしゃの（　）を かいます。', ['きっぷ', 'きぷ'], 0, '🎫', 'でんしゃの きっぷを かいます'),
  q('s05', 'sokuon', '（　）が でました。', ['つき', 'っき'], 0, '🌙', 'つきが でました'),
  q('s06', 'sokuon', '（　）で べんきょうします。', ['つくえ', 'っくえ'], 0, '🪑', 'つくえで べんきょうします'),
  q('s07', 'sokuon', '（　）で あそびます。', ['さっかー', 'さかー'], 0, '⚽', 'さっかーで あそびます'),
  q('s08', 'sokuon', '（　）に おちゃを いれます。', ['こっぷ', 'こぷ'], 0, '🥤', 'こっぷに おちゃを いれます'),
  q('s09', 'sokuon', '（　）で ねます。', ['べっど', 'べど'], 0, '🛏️', 'べっどで ねます'),
  q('s10', 'sokuon', 'てを（　）で あらいます。', ['せっけん', 'せけん'], 0, '🧼', 'てを せっけんで あらいます'),
  q('s11', 'sokuon', '（　）を たべます。', ['まっちゃ', 'まちゃ'], 0, '🍵', 'まっちゃを たべます'),
  q('s12', 'sokuon', '（　）で おちゃを のみます。', ['きっさてん', 'きさてん'], 0, '☕', 'きっさてんで おちゃを のみます'),
  q('s13', 'sokuon', 'とりの（　）が ひろがります。', ['つばさ', 'っばさ'], 0, '🕊️', 'とりの つばさが ひろがります'),
  q('s14', 'sokuon', '（　）を きります。', ['つめ', 'っめ'], 0, '💅', 'つめを きります'),
  q('s15', 'sokuon', 'いぬが（　）を ふります。', ['しっぽ', 'しぽ'], 0, '🐕', 'いぬが しっぽを ふります'),
  q('s16', 'sokuon', '（　）たべたいです。', ['もっと', 'もと'], 0, '🍽️', 'もっと たべたいです'),

  // 長音：短い文の空欄に、正しい語を入れる。
  q('c01', 'choon', '（　）が かえって きました。', ['おとうさん', 'おとおさん'], 0, '👨', 'おとうさんが かえって きました'),
  q('c02', 'choon', '（　）と あそびます。', ['おとうと', 'おとおと'], 0, '👦', 'おとうとと あそびます'),
  q('c03', 'choon', '（　）で あそびます。', ['こうえん', 'こおえん'], 0, '🛝', 'こうえんで あそびます'),
  q('c04', 'choon', 'あたまに（　）を かぶります。', ['ぼうし', 'ぼおし'], 0, '🧢', 'あたまに ぼうしを かぶります'),
  q('c05', 'choon', 'へやの（　）を します。', ['そうじ', 'そおじ'], 0, '🧹', 'へやの そうじを します'),
  q('c06', 'choon', '（　）に おはなしを ききます。', ['せんせい', 'せんせえ'], 0, '🧑‍🏫', 'せんせいに おはなしを ききます'),
  q('c07', 'choon', '（　）を みます。', ['とけい', 'とけえ'], 0, '🕰️', 'とけいを みます'),
  q('c08', 'choon', 'ともだちと（　）を みます。', ['えいが', 'ええが'], 0, '🎬', 'ともだちと えいがを みます'),
  q('c09', 'choon', 'ぞうは（　）です。', ['おおきい', 'おうきい'], 0, '🐘', 'ぞうは おおきいです'),
  q('c10', 'choon', 'もりに（　）が います。', ['おおかみ', 'おうかみ'], 0, '🐺', 'もりに おおかみが います'),
  q('c11', 'choon', 'やまが（　）です。', ['とおい', 'とうい'], 0, '🗻', 'やまが とおいです'),
  q('c12', 'choon', 'つめたい（　）を さわります。', ['こおり', 'こうり'], 0, '🧊', 'つめたい こおりを さわります'),
  q('c13', 'choon', '（　）に てを ふります。', ['おねえさん', 'おねいさん'], 0, '👩', 'おねえさんに てを ふります'),
  q('c14', 'choon', '（　）を さわります。', ['ほお', 'ほう'], 0, '😊', 'ほおを さわります'),
  q('c15', 'choon', 'りんごが（　）です。', ['おおい', 'おうい'], 0, '🍎', 'りんごが おおいです'),
  q('c16', 'choon', 'みちを（　）て いきます。', ['とおって', 'とうって'], 0, '🚪', 'みちを とおって いきます')
];

export const BADGES = [
  { id: 'kuttsuki-clear', name: 'ことば つなぎ', hint: 'くっつきことばを 1かい おわる', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/japanese/words-connect/badge.png' },
  { id: 'youon-clear', name: 'ちいさいもじ はっけん', hint: 'ちいさい「ゃゅょ」を 1かい おわる', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/japanese/word-detective/badge.png' },
  { id: 'sokuon-clear', name: 'ことばの リズム', hint: 'ちいさい「っ」を 1かい おわる', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/japanese/language-rhythm/badge.png' },
  { id: 'choon-clear', name: 'ていねい かな', hint: 'のばすおとを 1かい おわる', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/japanese/careful-writing/badge.png' },
  { id: 'first-step', name: 'はじめの いっぽ', hint: 'はじめて 10もん おわる', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/first-step/badge.png' },
  { id: 'two-stages', name: 'ふたつ クリア', hint: '2つの ステージを おわる', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/clear/badge.png' },
  { id: 'three-stages', name: 'あと ひとつ！', hint: '3つの ステージを おわる', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/mission-complete/badge.png' },
  { id: 'moji-master', name: 'もじマスター', hint: '4つの ステージを おわる', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/mastery/badge.png' },
  { id: 'score-five', name: 'いい ちょうし', hint: '1かいで 5もん せいかい', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/great-answer/badge.png' },
  { id: 'score-seven', name: 'しっかり かな', hint: '1かいで 7もん せいかい', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/accuracy/badge.png' },
  { id: 'score-nine', name: 'あと いっぽ！', hint: '1かいで 9もん せいかい', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/champion/badge.png' },
  { id: 'perfect', name: 'かんぺき！', hint: '10もん ぜんぶ せいかい', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/perfect/badge.png' },
  { id: 'play-two', name: 'もう いっかい', hint: 'あわせて 2かい あそぶ', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/challenger/badge.png' },
  { id: 'play-three', name: 'こつこつ かな', hint: 'あわせて 3かい あそぶ', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/steady-progress/badge.png' },
  { id: 'play-five', name: 'がんばりや', hint: 'あわせて 5かい あそぶ', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/hard-worker/badge.png' },
  { id: 'play-eight', name: 'れんしゅう めいじん', hint: 'あわせて 8かい あそぶ', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/practice-master/badge.png' },
  { id: 'play-twelve', name: 'かな しゅうかん', hint: 'あわせて 12かい あそぶ', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/streak/badge.png' },
  { id: 'play-twenty', name: 'ずっと ちょうせん', hint: 'あわせて 20かい あそぶ', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/keep-going/badge.png' },
  { id: 'correct-ten', name: '10この ことば', hint: 'あわせて 10もん せいかい', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/knowledge/badge.png' },
  { id: 'correct-twenty-five', name: 'ことばの め', hint: 'あわせて 25もん せいかい', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/japanese/word-sprout/badge.png' },
  { id: 'correct-fifty', name: 'ことばの き', hint: 'あわせて 50もん せいかい', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/japanese/word-tree/badge.png' },
  { id: 'correct-eighty', name: 'かな たんけんか', hint: 'あわせて 80もん せいかい', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/japanese/language-explorer/badge.png' },
  { id: 'correct-one-twenty', name: 'ことば しょくにん', hint: 'あわせて 120もん せいかい', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/japanese/word-weaver/badge.png' },
  { id: 'try-again', name: 'まちがいも だいじ', hint: 'まちがえても さいごまで がんばる', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/try-again/badge.png' },
  { id: 'review-correct', name: 'できたに かわった', hint: 'まえに まちがえた もんだいに せいかい', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/japanese/self-correction/badge.png' },
  { id: 'kuttsuki-twice', name: 'つなぎ はかせ', hint: 'くっつきことばを 2かい おわる', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/connection/badge.png' },
  { id: 'youon-twice', name: 'こもじ はかせ', hint: 'ちいさい「ゃゅょ」を 2かい おわる', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/discovery/badge.png' },
  { id: 'sokuon-twice', name: 'つまるおと はかせ', hint: 'ちいさい「っ」を 2かい おわる', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/focus/badge.png' },
  { id: 'choon-twice', name: 'のばすおと はかせ', hint: 'のばすおとを 2かい おわる', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/common/observer/badge.png' },
  { id: 'listen-three', name: 'みみで ことば', hint: '「きく」を 3かい つかう', image: 'https://tt-sensei.github.io/edu-assets/assets/badges/japanese/reading-aloud/badge.png' }
];
